### ISSUE TITLE
create a way to delete smth from arrays in db

### ISSUE THREAD

**Issue by RomaZinkevich** [bababubudev/Saucy_Delights#20]

**Comment by bababubudev** [comment]
We could make a put request where we pass an array as a parameter. I checked online and this is how you can pass arrays:
http://example.com/?data[0]=1&data[1]=2

**Comment by RomaZinkevich** [comment]
Already done, forgot to mention. If client side wants to delete smth in array it needs to send index with PUT request with negative sign.
